/**
 * The pool of first names used to populate a casefile.
 *
 * Constraints that matter for the puzzle:
 *  - letters only (clues talk about letters, vowels and repeats)
 *  - 3 to 9 characters, so a name always fits a grid cell on a phone
 *  - a deliberate spread of lengths, initials, double letters and vowel counts
 *    so that every clue type has something to bite on
 */
const RAW_NAMES = [
  "Aaron", "Abbie", "Abel", "Abigail", "Ada", "Adam", "Adele", "Adrian", "Agatha", "Agnes",
  "Aidan", "Aisha", "Alan", "Albert", "Alec", "Alexa", "Alfie", "Alfred", "Alice", "Alina",
  "Alison", "Allan", "Amber", "Amelia", "Amir", "Amos", "Amy", "Ana", "Anders", "Andre",
  "Andrea", "Andrew", "Angela", "Angus", "Anita", "Ann", "Anna", "Annabel", "Anne", "Annie",
  "Anthony", "Antonia", "April", "Archie", "Aria", "Ariel", "Arlo", "Arnold", "Arthur", "Asa",
  "Ash", "Asher", "Ashley", "Astrid", "Aubrey", "Audrey", "August", "Aurora", "Austin", "Ava",
  "Avery", "Axel", "Bailey", "Barbara", "Barney", "Barry", "Basil", "Beatrix", "Becca", "Bella",
  "Ben", "Benny", "Bernard", "Bert", "Bertha", "Bess", "Bethany", "Betsy", "Bettina", "Betty",
  "Bianca", "Bill", "Billie", "Blaine", "Blake", "Blanche", "Bo", "Bobby", "Bonnie", "Boris",
  "Bradley", "Bram", "Brenda", "Brendan", "Brett", "Brian", "Bridget", "Brody", "Brooke", "Bruce",
  "Bruno", "Bryan", "Bryony", "Caleb", "Callum", "Calvin", "Cameron", "Camilla", "Candice", "Cara",
  "Carl", "Carla", "Carlos", "Carmen", "Carol", "Caroline", "Carrie", "Carter", "Casey", "Cassie",
  "Cecil", "Cecilia", "Cedric", "Celia", "Cesar", "Chad", "Charles", "Charlie", "Chelsea", "Chester",
  "Chloe", "Chris", "Christie", "Cindy", "Claire", "Clara", "Clarence", "Clark", "Claude", "Claudia",
  "Clifford", "Clive", "Clyde", "Cody", "Cole", "Colin", "Connie", "Connor", "Conrad", "Cora",
  "Corey", "Cormac", "Craig", "Crystal", "Curtis", "Cyril", "Cyrus", "Dahlia", "Daisy", "Dale",
  "Damian", "Damon", "Dan", "Dana", "Daniel", "Danielle", "Danny", "Daphne", "Darcy", "Daria",
  "Darius", "Darren", "Dave", "David", "Dawn", "Dean", "Debbie", "Deborah", "Declan", "Delia",
  "Della", "Demi", "Denise", "Dennis", "Derek", "Desmond", "Dexter", "Diana", "Diane", "Diego",
  "Dilan", "Dina", "Dion", "Dolly", "Dolores", "Dominic", "Don", "Donald", "Donna", "Dora",
  "Doreen", "Doris", "Dorothy", "Dougal", "Douglas", "Drew", "Duane", "Dudley", "Duncan", "Dustin",
  "Dylan", "Eamon", "Earl", "Ebony", "Ed", "Eddie", "Eden", "Edgar", "Edith", "Edmund",
  "Edna", "Eduardo", "Edward", "Edwin", "Effie", "Egon", "Eileen", "Elaine", "Eleanor", "Elena",
  "Eli", "Elias", "Elijah", "Elise", "Eliza", "Ella", "Ellen", "Ellie", "Elliot", "Elmer",
  "Eloise", "Elsa", "Elsie", "Elton", "Elvira", "Elvis", "Emerson", "Emil", "Emilia", "Emily",
  "Emma", "Emmett", "Enid", "Enzo", "Eric", "Erica", "Erik", "Erin", "Ernest", "Errol",
  "Esme", "Esther", "Ethan", "Ethel", "Etta", "Eugene", "Eunice", "Eva", "Evan", "Eve",
  "Evelyn", "Everett", "Ezra", "Fabian", "Faith", "Fay", "Felicity", "Felix", "Fergus", "Fern",
  "Fernando", "Finlay", "Finn", "Fiona", "Flora", "Florence", "Floyd", "Forrest", "Frances", "Francis",
  "Frank", "Frankie", "Franklin", "Fraser", "Fred", "Freddie", "Frederic", "Freya", "Gabriel", "Gail",
  "Gareth", "Garrett", "Gary", "Gavin", "Gemma", "Gene", "Geoffrey", "George", "Georgia", "Gerald",
  "Gerard", "Gertrude", "Gilbert", "Giles", "Gina", "Ginger", "Gladys", "Glen", "Glenda", "Gloria",
  "Godfrey", "Gordon", "Grace", "Grant", "Greg", "Gregory", "Greta", "Griffin", "Guy", "Gwen",
  "Hadley", "Hal", "Haley", "Hank", "Hannah", "Harlan", "Harold", "Harper", "Harriet", "Harris",
  "Harry", "Harvey", "Hattie", "Hazel", "Heather", "Hector", "Heidi", "Helen", "Helena", "Henry",
  "Herbert", "Herman", "Hester", "Hilary", "Hilda", "Holly", "Homer", "Honor", "Hope", "Horace",
  "Howard", "Hubert", "Hugh", "Hugo", "Humphrey", "Hunter", "Ian", "Ida", "Idris", "Ignatius",
  "Ilona", "Imogen", "India", "Ingrid", "Irene", "Iris", "Irma", "Irving", "Isaac", "Isabel",
  "Isla", "Ismael", "Ivan", "Ivy", "Jack", "Jackie", "Jacob", "Jade", "Jake", "James",
  "Jamie", "Jan", "Jane", "Janet", "Janice", "Jared", "Jasmine", "Jason", "Jasper", "Javier",
  "Jay", "Jean", "Jeff", "Jemima", "Jenna", "Jennifer", "Jenny", "Jeremy", "Jerome", "Jerry",
  "Jesse", "Jessica", "Jill", "Jim", "Jimmy", "Jo", "Joan", "Joanna", "Jocelyn", "Jodie",
  "Joel", "Johanna", "John", "Johnny", "Jolene", "Jonah", "Jonas", "Jordan", "Jorge", "Jose",
  "Joseph", "Josie", "Joyce", "Juan", "Judith", "Judy", "Jules", "Julia", "Julian", "Julie",
  "June", "Justin", "Kai", "Kaitlyn", "Kara", "Karen", "Karl", "Kate", "Katherine", "Kathleen",
  "Kathy", "Katie", "Katrina", "Kay", "Keeley", "Keith", "Kelly", "Kelsey", "Ken", "Kendra",
  "Kenneth", "Kerry", "Kevin", "Kieran", "Kim", "Kirsten", "Kitty", "Klara", "Kurt", "Kyle",
  "Lacey", "Lachlan", "Laila", "Lana", "Lance", "Lara", "Larry", "Laura", "Lauren", "Laurence",
  "Lawrence", "Layla", "Leah", "Lee", "Leigh", "Leila", "Lena", "Lenny", "Leo", "Leon",
  "Leona", "Leonard", "Leroy", "Leslie", "Lester", "Lewis", "Lex", "Liam", "Libby", "Lila",
  "Lilian", "Lillie", "Lily", "Lina", "Linda", "Lindsay", "Lionel", "Lisa", "Liv", "Lloyd",
  "Logan", "Lois", "Lola", "Lorna", "Lorraine", "Lottie", "Louis", "Louisa", "Louise", "Lucas",
  "Lucia", "Lucille", "Lucy", "Luke", "Lula", "Luna", "Lydia", "Lyla", "Lynn", "Mabel",
  "Mac", "Maddie", "Madeline", "Madison", "Mae", "Maeve", "Magnus", "Maisie", "Malcolm", "Mandy",
  "Manuel", "Mara", "Marc", "Marcia", "Marco", "Marcus", "Margaret", "Margot", "Maria", "Mariah",
  "Marian", "Marilyn", "Marina", "Mario", "Marion", "Marissa", "Marjorie", "Mark", "Marlon", "Marsha",
  "Martha", "Martin", "Marvin", "Mary", "Mason", "Matilda", "Matt", "Matthew", "Maude", "Maureen",
  "Maurice", "Max", "Maxine", "May", "Maya", "Megan", "Mel", "Melanie", "Melissa", "Melody",
  "Mercy", "Meredith", "Merle", "Mia", "Micah", "Michael", "Michelle", "Mickey", "Miguel", "Mike",
  "Mila", "Mildred", "Miles", "Millie", "Milo", "Milton", "Mimi", "Mindy", "Minnie", "Miranda",
  "Miriam", "Misha", "Mitchell", "Moira", "Mollie", "Molly", "Mona", "Monica", "Monique", "Morgan",
  "Morris", "Mortimer", "Morton", "Moses", "Muriel", "Murray", "Myra", "Myrtle", "Nadia", "Nadine",
  "Nancy", "Naomi", "Natalie", "Nathan", "Neil", "Nell", "Nelly", "Nelson", "Nessa", "Nettie",
  "Neville", "Niall", "Nicholas", "Nick", "Nicola", "Nicole", "Nigel", "Nina", "Noah", "Noel",
  "Nolan", "Nora", "Norma", "Norman", "Norris", "Octavia", "Odette", "Olga", "Olive", "Oliver",
  "Olivia", "Ollie", "Omar", "Ophelia", "Oscar", "Oswald", "Otis", "Otto", "Owen", "Ozzy",
  "Pablo", "Paddy", "Paige", "Pamela", "Paolo", "Pat", "Patricia", "Patrick", "Patsy", "Paul",
  "Paula", "Pauline", "Pearl", "Pedro", "Peggy", "Penelope", "Penny", "Percy", "Perry", "Pete",
  "Peter", "Petra", "Phil", "Philip", "Phoebe", "Phyllis", "Pierce", "Pierre", "Piper", "Polly",
  "Poppy", "Portia", "Preston", "Primrose", "Priscila", "Quentin", "Quincy", "Quinn", "Rachel", "Rae",
  "Rafael", "Ralph", "Ramona", "Randall", "Randy", "Raoul", "Raphael", "Raquel", "Raul", "Ray",
  "Raymond", "Reba", "Rebecca", "Reece", "Reed", "Reggie", "Regina", "Reid", "Rena", "Rene",
  "Renee", "Reuben", "Rex", "Rhett", "Rhoda", "Rhonda", "Rhys", "Ricardo", "Rich", "Richard",
  "Rick", "Rickie", "Rita", "River", "Roberta", "Roberto", "Robin", "Robyn", "Rocco", "Rochelle",
  "Rod", "Roderick", "Rodney", "Roger", "Roland", "Rolf", "Roman", "Ron", "Ronald", "Ronnie",
  "Rory", "Rosa", "Rosalie", "Rosalind", "Rose", "Rosemary", "Rosie", "Ross", "Rowan", "Rowena",
  "Roxanne", "Roy", "Ruben", "Ruby", "Rudy", "Rufus", "Rupert", "Russell", "Ruth", "Ryan",
  "Sabrina", "Sadie", "Sally", "Salvador", "Sam", "Samantha", "Samir", "Samson", "Samuel", "Sandra",
  "Sandy", "Santiago", "Sara", "Sarah", "Sasha", "Saul", "Scarlett", "Scott", "Sean", "Sebastian",
  "Selena", "Selina", "Serena", "Seth", "Seymour", "Shane", "Shannon", "Sharon", "Shaun", "Sheila",
  "Shelby", "Sheldon", "Shelley", "Sheridan", "Sherman", "Sherry", "Shirley", "Sidney", "Sienna", "Sierra",
  "Silas", "Simon", "Simone", "Sinead", "Skye", "Sofia", "Sol", "Solomon", "Sonia", "Sonny",
  "Sophie", "Spencer", "Stacey", "Stanley", "Stefan", "Stella", "Stephen", "Steve", "Stewart", "Stuart",
  "Sue", "Sullivan", "Summer", "Susan", "Susanna", "Suzanne", "Sybil", "Sylvia", "Tabitha", "Tamara",
  "Tammy", "Tanya", "Tara", "Tate", "Taylor", "Ted", "Teddy", "Terence", "Teresa", "Terry",
  "Tess", "Tessa", "Thea", "Thelma", "Theo", "Theodore", "Theresa", "Thomas", "Tia", "Tiffany",
  "Tim", "Timothy", "Tina", "Tobias", "Toby", "Todd", "Tom", "Tommy", "Toni", "Tony",
  "Tracy", "Travis", "Trent", "Trevor", "Tricia", "Trinity", "Trisha", "Tristan", "Troy", "Trudy",
  "Tucker", "Tyler", "Tyra", "Ulrich", "Ulysses", "Una", "Ursula", "Val", "Valentin", "Valerie",
  "Vanessa", "Vaughn", "Velma", "Vera", "Vernon", "Veronica", "Vicky", "Victor", "Victoria", "Vince",
  "Vincent", "Viola", "Violet", "Virgil", "Virginia", "Vivian", "Vivienne", "Wade", "Walter", "Wanda",
  "Ward", "Warren", "Wayne", "Wendell", "Wendy", "Wesley", "Whitney", "Wilbur", "Wilfred", "Will",
  "Willa", "William", "Willie", "Willow", "Wilma", "Wilson", "Winifred", "Winston", "Woody", "Wyatt",
  "Xander", "Xavier", "Xena", "Yasmin", "Yolanda", "York", "Yves", "Yvette", "Yvonne", "Zach",
  "Zachary", "Zane", "Zara", "Zeke", "Zelda", "Zena", "Zoe", "Zola", "Zora", "Zack",

  // A second pass, widening the pool past the largest casefile so that even a
  // 1,440-name Inspector file can be mostly distinct names.
  "Abraham", "Adela", "Adrienne", "Agustin", "Ahmed", "Aileen", "Aimee", "Ainsley", "Alba", "Alberto",
  "Albie", "Aldo", "Aled", "Alessia", "Alexis", "Alfonso", "Ali", "Alicia", "Alma", "Alonso",
  "Aloysius", "Alton", "Alvaro", "Alvin", "Alyssa", "Amanda", "Amara", "Ambrose", "Amelie", "Amina",
  "Amira", "Ammar", "Amrit", "Anais", "Anastasia", "Anatole", "Andrei", "Aneta", "Angelo", "Anika",
  "Anouk", "Anselm", "Anthea", "Antoine", "Anton", "Antony", "Anwen", "Aoife", "Apollo", "Araminta",
  "Archer", "Arden", "Ari", "Arianne", "Arjun", "Arlene", "Armand", "Arnaud", "Arne", "Aron",
  "Arran", "Artemis", "Arun", "Ashton", "Aslan", "Astor", "Athena", "Aurelia", "Aurelio", "Averil",
  "Avril", "Ayesha", "Azra", "Bao", "Barnaby", "Bartek", "Baxter", "Bea", "Beatrice", "Beau",
  "Belinda", "Benedict", "Benito", "Benjamin", "Benoit", "Berenice", "Bernie", "Bertram", "Beryl", "Bethan",
  "Bettie", "Birgit", "Bjorn", "Blair", "Blanca", "Blythe", "Bodhi", "Boyd", "Brandon", "Branwen",
  "Brianna", "Brice", "Bridie", "Brigid", "Britt", "Bronwen", "Bryce", "Bryn", "Buster", "Byron",
  "Cadence", "Caitlin", "Calla", "Callie", "Camden", "Camille", "Candace", "Caoimhe", "Caprice", "Carina",
  "Carlotta", "Carmela", "Carys", "Casimir", "Caspar", "Cassian", "Cassius", "Catalina", "Cathal", "Cato",
  "Catrin", "Cecile", "Celeste", "Celine", "Cerys", "Cesare", "Chandra", "Chantal", "Charity", "Charlton",
  "Chase", "Chiara", "Christy", "Cian", "Ciara", "Cillian", "Clemence", "Clement", "Cleo", "Clifton",
  "Clover", "Colette", "Colm", "Columba", "Connell", "Constance", "Cooper", "Corinne", "Cosima", "Cosmo",
  "Crispin", "Cruz", "Cyra", "Dagmar", "Dai", "Daichi", "Daisuke", "Dalia", "Dallas", "Damaris",
  "Damien", "Danica", "Dante", "Danya", "Darcey", "Dario", "Darla", "Darnell", "Daryl", "Davina",
  "Dawson", "Deacon", "Deirdre", "Delphine", "Demetrius", "Denver", "Derry", "Desiree", "Devon", "Dewi",
  "Dhruv", "Diarmuid", "Dieter", "Dilys", "Dimitri", "Dinah", "Django", "Dmitri", "Dominik", "Donal",
  "Donovan", "Dorian", "Dougie", "Drusilla", "Duke", "Dulcie", "Dusty", "Eabha", "Eamonn", "Earnest",
  "Eartha", "Ebba", "Edie", "Edmond", "Edouard", "Eero", "Efram", "Egbert", "Eiden", "Eira",
  "Eirlys", "Elara", "Elder", "Eldon", "Eleanora", "Elian", "Elif", "Elin", "Eliot", "Ellery",
  "Elliott", "Elodie", "Elowen", "Eloy", "Elspeth", "Emeline", "Emiliano", "Emlyn", "Emory", "Enda",
  "Endre", "Enrico", "Enrique", "Eoin", "Ephraim", "Erasmus", "Erikson", "Ernesto", "Esben", "Esmee",
  "Esperanza", "Essie", "Esteban", "Estelle", "Etienne", "Euan", "Eugenia", "Eulalia", "Evander", "Everard",
  "Ewan", "Ezekiel", "Fabien", "Fabiola", "Fallon", "Fanny", "Farrah", "Faye", "Federico", "Felipe",
  "Fenella", "Ferdinand", "Fidel", "Fielding", "Filip", "Finbar", "Finnian", "Fionn", "Fletcher", "Fleur",
  "Flynn", "Fola", "Forbes", "Ford", "Fran", "Franco", "Freddy", "Frida", "Frieda", "Fritz",
  "Fyodor", "Gabriela", "Gaia", "Galen", "Garcia", "Gaspard", "Gaston", "Gavriel", "Genevieve", "Geoff",
  "Georgina", "Geraldine", "Gerhard", "Gertie", "Gethin", "Gia", "Gideon", "Gilda", "Gillian", "Gino",
  "Giovanni", "Gisela", "Giulia", "Godwin", "Golda", "Goran", "Grady", "Graeme", "Gray", "Gregor",
  "Griselda", "Guido", "Gunnar", "Gustav", "Gwendolen", "Gwilym", "Gwyneth", "Hadrian", "Hafsa", "Hakim",
  "Halima", "Hamish", "Hamza", "Hana", "Hanna", "Hanne", "Hannelore", "Harlow", "Harmony", "Haroun",
  "Haruki", "Hassan", "Havana", "Haven", "Hayden", "Heath", "Hedda", "Hedy", "Heinrich", "Helga",
  "Hendrik", "Henrietta", "Hera", "Hermione", "Hero", "Hesper", "Hettie", "Hidalgo", "Hilde", "Hollis",
  "Honora", "Horatio", "Hoshi", "Humbert", "Hyacinth", "Iain", "Ibrahim", "Ignacio", "Igor", "Ilana",
  "Ilias", "Ilse", "Imani", "Imelda", "Imran", "Ina", "Indigo", "Ines", "Inez", "Ingmar",
  "Iolo", "Iona", "Ione", "Irina", "Isaiah", "Iseult", "Isidore", "Isobel", "Israel", "Itzel",
  "Ivar", "Ivo", "Izzy", "Jacinta", "Jacinto", "Jaden", "Jago", "Jamal", "Jamila", "Janus",
  "Jarrah", "Jarvis", "Javed", "Jaya", "Jaz", "Jedidiah", "Jem", "Jemma", "Jensen", "Jericho",
  "Jesper", "Jetta", "Jia", "Jian", "Jimena", "Joaquin", "Jocasta", "Jody", "Johan", "Jolyon",
  "Jonty", "Jorja", "Josefa", "Joss", "Jovan", "Juanita", "Judah", "Juliet", "Juno", "Jurgen",
  "Justine", "Kaia", "Kalani", "Kalila", "Kamal", "Kamila", "Kane", "Karim", "Karina", "Kasia",
  "Kasper", "Katia", "Kayla", "Keanu", "Keegan", "Keiko", "Kellan", "Kenji", "Kenzo", "Keren",
  "Kerensa", "Kester", "Khalid", "Kiera", "Kieron", "Kiki", "Kilian", "Kimiko", "Kingsley", "Kiran",
  "Kirby", "Kirsty", "Kit", "Klaus", "Knox", "Kofi", "Konrad", "Krista", "Kristof", "Kwame",
  "Kyra", "Lakshmi", "Lalita", "Lamar", "Lambert", "Lando", "Larkin", "Lars", "Laszlo", "Latif",
  "Laurel", "Laurie", "Lavinia", "Leandro", "Leif", "Lennon", "Lennox", "Lenore", "Leonie", "Leonora",
  "Leopold", "Levi", "Liana", "Lidia", "Liesel", "Lilith", "Linus", "Lior", "Lisbeth", "Livia",
  "Llewelyn", "Loki", "Lorcan", "Lorenzo", "Loretta", "Lowri", "Luca", "Lucian", "Lucinda", "Ludo",
  "Ludwig", "Luella", "Luka", "Lukas", "Lumi", "Lyra", "Lysander", "Mabli", "Maddox", "Madeleine",
  "Madoc", "Magda", "Magdalena", "Maggie", "Magnolia", "Mahdi", "Maia", "Maira", "Makoto", "Malachi",
  "Malin", "Mallory", "Manon", "Manuela", "Marcel", "Marek", "Margit", "Mariam", "Marianne", "Marika",
  "Mariko", "Marisol", "Marius", "Marlow", "Marnie", "Marta", "Martina", "Masha", "Mateo", "Mathias",
  "Matteo", "Maud", "Maxim", "Mayra", "Meera", "Mehmet", "Meira", "Melina", "Melisande", "Mercedes",
  "Merida", "Merrick", "Merry", "Mervyn", "Meryl", "Micaela", "Michal", "Mikael", "Mikkel", "Milena",
  "Mira", "Mirabel", "Mirella", "Mirko", "Misael", "Mitra", "Montague", "Morag", "Morwenna", "Mostafa",
  "Murphy", "Mustafa", "Myfanwy", "Myles", "Naima", "Nakia", "Nala", "Nalini", "Nancie", "Nando",
  "Naoise", "Naoko", "Narcissa", "Nasir", "Natasha", "Nathaniel", "Navid", "Nazir", "Neave", "Nemo",
  "Nerys", "Nestor", "Neve", "Niamh", "Nico", "Nikita", "Nikolai", "Nils", "Nira", "Nita",
  "Noam", "Noor", "Norbert", "Nova", "Nuala", "Nyla", "Oakley", "Obadiah", "Oceane", "Octave",
  "Odile", "Odin", "Ofelia", "Oisin", "Olaf", "Oleg", "Olwen", "Omari", "Ondine", "Onyx",
  "Oona", "Opal", "Oren", "Orla", "Orson", "Osian", "Osman", "Ottilie", "Ovid", "Owain",
  "Ozan", "Padma", "Paloma", "Pandora", "Panos", "Paris", "Parker", "Pascal", "Patience", "Paulo",
  "Pavel", "Paz", "Pearce", "Pelle", "Penn", "Perdita", "Peregrine", "Phaedra", "Phineas", "Pia",
  "Pilar", "Pippa", "Piran", "Placido", "Poe", "Porter", "Prakash", "Priya", "Prosper", "Prudence",
  "Pryce", "Quill", "Quinlan", "Quinta", "Quirin", "Rafferty", "Ragnar", "Raina", "Raisa", "Raj",
  "Ramiro", "Ramsey", "Ranulph", "Raphaela", "Rasmus", "Raven", "Ravi", "Rayan", "Reeva", "Regan",
  "Reilly", "Remi", "Remus", "Renata", "Rhian", "Rhiannon", "Rhona", "Riaz", "Rider", "Riley",
  "Rina", "Rio", "Riva", "Roan", "Robbie", "Rocio", "Roderigo", "Roisin", "Rolando", "Romilly",
  "Romy", "Ronan", "Rooney", "Rosaline", "Roscoe", "Roshan", "Rosina", "Roxana", "Ruaridh", "Rudolf",
  "Rumi", "Runa", "Rurik", "Ryder", "Ryo", "Sable", "Sadhbh", "Saffron", "Sahar", "Saira",
  "Salim", "Salome", "Samara", "Sameer", "Samira", "Sanna", "Santo", "Saoirse", "Sapphire", "Sarai",
  "Saskia", "Savannah", "Sayuri", "Scarlet", "Seamus", "Seb", "Senga", "Seraphina", "Seren", "Serge",
  "Sergei", "Shakira", "Shamus", "Shania", "Shaw", "Shea", "Sheena", "Shona", "Sian", "Sibyl",
  "Sidonie", "Siena", "Sigrid", "Silvia", "Simeon", "Sinclair", "Siobhan", "Sissy", "Sofie", "Solveig",
  "Sonja", "Soraya", "Sorcha", "Spike", "Stefano", "Stellan", "Stig", "Sunniva", "Susannah", "Svea",
  "Sven", "Sylvain", "Tabby", "Tadeo", "Taj", "Talia", "Talitha", "Tallulah", "Tamar", "Tamsin",
  "Tanvir", "Tariq", "Tarquin", "Tasha", "Tatiana", "Tavish", "Teagan", "Tegan", "Tekla", "Teodoro",
  "Terrence", "Tessie", "Thaddeus", "Thandi", "Themba", "Theresia", "Thierry", "Thom", "Thora", "Thurston",
  "Tiago", "Tibor", "Tierney", "Tilda", "Tilly", "Timo", "Tirion", "Tito", "Tobin", "Toma",
  "Tomasz", "Topaz", "Torin", "Toshi", "Tova", "Trixie", "Tudor", "Tulip", "Turlough", "Tyrell",
  "Ulla", "Ulrike", "Umar", "Unity", "Uriel", "Ursa", "Usman", "Uzma", "Vada", "Valentina",
  "Valeria", "Vanja", "Varun", "Vashti", "Vaughan", "Velvet", "Venetia", "Verity", "Vesna", "Vidal",
  "Vidya", "Viggo", "Vikram", "Vilhelm", "Vinnie", "Viorica", "Virgilio", "Vita", "Vito", "Vivien",
  "Vlad", "Wallis", "Walton", "Waverly", "Whitaker", "Wilbert", "Wilhelm", "Willem", "Winnie", "Wolfgang",
  "Wren", "Wyn", "Xanthe", "Ximena", "Xiomara", "Xola", "Yara", "Yaron", "Yasir", "Yasmine",
  "Yohan", "Yoko", "Yolande", "Yosef", "Yuki", "Yuri", "Yusuf", "Yvain", "Zadie", "Zahra",
  "Zain", "Zainab", "Zander", "Zavier", "Zayn", "Zeb", "Zephyr", "Zia", "Zillah", "Zinnia",
  "Zita", "Ziva", "Zoltan", "Zsofia", "Zuri",
] as const;

function isUsable(name: string): boolean {
  return /^[A-Za-z]{2,9}$/.test(name);
}

/** Deduplicated, validated, alphabetically stable name pool. */
export const NAME_POOL: readonly string[] = Array.from(new Set(RAW_NAMES))
  .filter(isUsable)
  .sort((a, b) => a.localeCompare(b, "en"));
