/**
 * The pool of first names used to populate a casefile.
 *
 * Constraints that matter for the puzzle:
 *  - letters only (clues talk about letters, vowels and repeats)
 *  - 3 to 9 characters, so a name always fits a grid cell on a phone
 *  - a deliberate spread of lengths, initials, double letters and vowel counts
 *    so that every clue type has something to bite on
 */
const RAW_NAMES = [
  "Aaron", "Abbie", "Abel", "Abigail", "Ada", "Adam", "Adele", "Adrian", "Agatha", "Agnes",
  "Aidan", "Aisha", "Alan", "Albert", "Alec", "Alexa", "Alfie", "Alfred", "Alice", "Alina",
  "Alison", "Allan", "Amber", "Amelia", "Amir", "Amos", "Amy", "Ana", "Anders", "Andre",
  "Andrea", "Andrew", "Angela", "Angus", "Anita", "Ann", "Anna", "Annabel", "Anne", "Annie",
  "Anthony", "Antonia", "April", "Archie", "Aria", "Ariel", "Arlo", "Arnold", "Arthur", "Asa",
  "Ash", "Asher", "Ashley", "Astrid", "Aubrey", "Audrey", "August", "Aurora", "Austin", "Ava",
  "Avery", "Axel", "Bailey", "Barbara", "Barney", "Barry", "Basil", "Beatrix", "Becca", "Bella",
  "Ben", "Benny", "Bernard", "Bert", "Bertha", "Bess", "Bethany", "Betsy", "Bettina", "Betty",
  "Bianca", "Bill", "Billie", "Blaine", "Blake", "Blanche", "Bo", "Bobby", "Bonnie", "Boris",
  "Bradley", "Bram", "Brenda", "Brendan", "Brett", "Brian", "Bridget", "Brody", "Brooke", "Bruce",
  "Bruno", "Bryan", "Bryony", "Caleb", "Callum", "Calvin", "Cameron", "Camilla", "Candice", "Cara",
  "Carl", "Carla", "Carlos", "Carmen", "Carol", "Caroline", "Carrie", "Carter", "Casey", "Cassie",
  "Cecil", "Cecilia", "Cedric", "Celia", "Cesar", "Chad", "Charles", "Charlie", "Chelsea", "Chester",
  "Chloe", "Chris", "Christie", "Cindy", "Claire", "Clara", "Clarence", "Clark", "Claude", "Claudia",
  "Clifford", "Clive", "Clyde", "Cody", "Cole", "Colin", "Connie", "Connor", "Conrad", "Cora",
  "Corey", "Cormac", "Craig", "Crystal", "Curtis", "Cyril", "Cyrus", "Dahlia", "Daisy", "Dale",
  "Damian", "Damon", "Dan", "Dana", "Daniel", "Danielle", "Danny", "Daphne", "Darcy", "Daria",
  "Darius", "Darren", "Dave", "David", "Dawn", "Dean", "Debbie", "Deborah", "Declan", "Delia",
  "Della", "Demi", "Denise", "Dennis", "Derek", "Desmond", "Dexter", "Diana", "Diane", "Diego",
  "Dilan", "Dina", "Dion", "Dolly", "Dolores", "Dominic", "Don", "Donald", "Donna", "Dora",
  "Doreen", "Doris", "Dorothy", "Dougal", "Douglas", "Drew", "Duane", "Dudley", "Duncan", "Dustin",
  "Dylan", "Eamon", "Earl", "Ebony", "Ed", "Eddie", "Eden", "Edgar", "Edith", "Edmund",
  "Edna", "Eduardo", "Edward", "Edwin", "Effie", "Egon", "Eileen", "Elaine", "Eleanor", "Elena",
  "Eli", "Elias", "Elijah", "Elise", "Eliza", "Ella", "Ellen", "Ellie", "Elliot", "Elmer",
  "Eloise", "Elsa", "Elsie", "Elton", "Elvira", "Elvis", "Emerson", "Emil", "Emilia", "Emily",
  "Emma", "Emmett", "Enid", "Enzo", "Eric", "Erica", "Erik", "Erin", "Ernest", "Errol",
  "Esme", "Esther", "Ethan", "Ethel", "Etta", "Eugene", "Eunice", "Eva", "Evan", "Eve",
  "Evelyn", "Everett", "Ezra", "Fabian", "Faith", "Fay", "Felicity", "Felix", "Fergus", "Fern",
  "Fernando", "Finlay", "Finn", "Fiona", "Flora", "Florence", "Floyd", "Forrest", "Frances", "Francis",
  "Frank", "Frankie", "Franklin", "Fraser", "Fred", "Freddie", "Frederic", "Freya", "Gabriel", "Gail",
  "Gareth", "Garrett", "Gary", "Gavin", "Gemma", "Gene", "Geoffrey", "George", "Georgia", "Gerald",
  "Gerard", "Gertrude", "Gilbert", "Giles", "Gina", "Ginger", "Gladys", "Glen", "Glenda", "Gloria",
  "Godfrey", "Gordon", "Grace", "Grant", "Greg", "Gregory", "Greta", "Griffin", "Guy", "Gwen",
  "Hadley", "Hal", "Haley", "Hank", "Hannah", "Harlan", "Harold", "Harper", "Harriet", "Harris",
  "Harry", "Harvey", "Hattie", "Hazel", "Heather", "Hector", "Heidi", "Helen", "Helena", "Henry",
  "Herbert", "Herman", "Hester", "Hilary", "Hilda", "Holly", "Homer", "Honor", "Hope", "Horace",
  "Howard", "Hubert", "Hugh", "Hugo", "Humphrey", "Hunter", "Ian", "Ida", "Idris", "Ignatius",
  "Ilona", "Imogen", "India", "Ingrid", "Irene", "Iris", "Irma", "Irving", "Isaac", "Isabel",
  "Isla", "Ismael", "Ivan", "Ivy", "Jack", "Jackie", "Jacob", "Jade", "Jake", "James",
  "Jamie", "Jan", "Jane", "Janet", "Janice", "Jared", "Jasmine", "Jason", "Jasper", "Javier",
  "Jay", "Jean", "Jeff", "Jemima", "Jenna", "Jennifer", "Jenny", "Jeremy", "Jerome", "Jerry",
  "Jesse", "Jessica", "Jill", "Jim", "Jimmy", "Jo", "Joan", "Joanna", "Jocelyn", "Jodie",
  "Joel", "Johanna", "John", "Johnny", "Jolene", "Jonah", "Jonas", "Jordan", "Jorge", "Jose",
  "Joseph", "Josie", "Joyce", "Juan", "Judith", "Judy", "Jules", "Julia", "Julian", "Julie",
  "June", "Justin", "Kai", "Kaitlyn", "Kara", "Karen", "Karl", "Kate", "Katherine", "Kathleen",
  "Kathy", "Katie", "Katrina", "Kay", "Keeley", "Keith", "Kelly", "Kelsey", "Ken", "Kendra",
  "Kenneth", "Kerry", "Kevin", "Kieran", "Kim", "Kirsten", "Kitty", "Klara", "Kurt", "Kyle",
  "Lacey", "Lachlan", "Laila", "Lana", "Lance", "Lara", "Larry", "Laura", "Lauren", "Laurence",
  "Lawrence", "Layla", "Leah", "Lee", "Leigh", "Leila", "Lena", "Lenny", "Leo", "Leon",
  "Leona", "Leonard", "Leroy", "Leslie", "Lester", "Lewis", "Lex", "Liam", "Libby", "Lila",
  "Lilian", "Lillie", "Lily", "Lina", "Linda", "Lindsay", "Lionel", "Lisa", "Liv", "Lloyd",
  "Logan", "Lois", "Lola", "Lorna", "Lorraine", "Lottie", "Louis", "Louisa", "Louise", "Lucas",
  "Lucia", "Lucille", "Lucy", "Luke", "Lula", "Luna", "Lydia", "Lyla", "Lynn", "Mabel",
  "Mac", "Maddie", "Madeline", "Madison", "Mae", "Maeve", "Magnus", "Maisie", "Malcolm", "Mandy",
  "Manuel", "Mara", "Marc", "Marcia", "Marco", "Marcus", "Margaret", "Margot", "Maria", "Mariah",
  "Marian", "Marilyn", "Marina", "Mario", "Marion", "Marissa", "Marjorie", "Mark", "Marlon", "Marsha",
  "Martha", "Martin", "Marvin", "Mary", "Mason", "Matilda", "Matt", "Matthew", "Maude", "Maureen",
  "Maurice", "Max", "Maxine", "May", "Maya", "Megan", "Mel", "Melanie", "Melissa", "Melody",
  "Mercy", "Meredith", "Merle", "Mia", "Micah", "Michael", "Michelle", "Mickey", "Miguel", "Mike",
  "Mila", "Mildred", "Miles", "Millie", "Milo", "Milton", "Mimi", "Mindy", "Minnie", "Miranda",
  "Miriam", "Misha", "Mitchell", "Moira", "Mollie", "Molly", "Mona", "Monica", "Monique", "Morgan",
  "Morris", "Mortimer", "Morton", "Moses", "Muriel", "Murray", "Myra", "Myrtle", "Nadia", "Nadine",
  "Nancy", "Naomi", "Natalie", "Nathan", "Neil", "Nell", "Nelly", "Nelson", "Nessa", "Nettie",
  "Neville", "Niall", "Nicholas", "Nick", "Nicola", "Nicole", "Nigel", "Nina", "Noah", "Noel",
  "Nolan", "Nora", "Norma", "Norman", "Norris", "Octavia", "Odette", "Olga", "Olive", "Oliver",
  "Olivia", "Ollie", "Omar", "Ophelia", "Oscar", "Oswald", "Otis", "Otto", "Owen", "Ozzy",
  "Pablo", "Paddy", "Paige", "Pamela", "Paolo", "Pat", "Patricia", "Patrick", "Patsy", "Paul",
  "Paula", "Pauline", "Pearl", "Pedro", "Peggy", "Penelope", "Penny", "Percy", "Perry", "Pete",
  "Peter", "Petra", "Phil", "Philip", "Phoebe", "Phyllis", "Pierce", "Pierre", "Piper", "Polly",
  "Poppy", "Portia", "Preston", "Primrose", "Priscila", "Quentin", "Quincy", "Quinn", "Rachel", "Rae",
  "Rafael", "Ralph", "Ramona", "Randall", "Randy", "Raoul", "Raphael", "Raquel", "Raul", "Ray",
  "Raymond", "Reba", "Rebecca", "Reece", "Reed", "Reggie", "Regina", "Reid", "Rena", "Rene",
  "Renee", "Reuben", "Rex", "Rhett", "Rhoda", "Rhonda", "Rhys", "Ricardo", "Rich", "Richard",
  "Rick", "Rickie", "Rita", "River", "Roberta", "Roberto", "Robin", "Robyn", "Rocco", "Rochelle",
  "Rod", "Roderick", "Rodney", "Roger", "Roland", "Rolf", "Roman", "Ron", "Ronald", "Ronnie",
  "Rory", "Rosa", "Rosalie", "Rosalind", "Rose", "Rosemary", "Rosie", "Ross", "Rowan", "Rowena",
  "Roxanne", "Roy", "Ruben", "Ruby", "Rudy", "Rufus", "Rupert", "Russell", "Ruth", "Ryan",
  "Sabrina", "Sadie", "Sally", "Salvador", "Sam", "Samantha", "Samir", "Samson", "Samuel", "Sandra",
  "Sandy", "Santiago", "Sara", "Sarah", "Sasha", "Saul", "Scarlett", "Scott", "Sean", "Sebastian",
  "Selena", "Selina", "Serena", "Seth", "Seymour", "Shane", "Shannon", "Sharon", "Shaun", "Sheila",
  "Shelby", "Sheldon", "Shelley", "Sheridan", "Sherman", "Sherry", "Shirley", "Sidney", "Sienna", "Sierra",
  "Silas", "Simon", "Simone", "Sinead", "Skye", "Sofia", "Sol", "Solomon", "Sonia", "Sonny",
  "Sophie", "Spencer", "Stacey", "Stanley", "Stefan", "Stella", "Stephen", "Steve", "Stewart", "Stuart",
  "Sue", "Sullivan", "Summer", "Susan", "Susanna", "Suzanne", "Sybil", "Sylvia", "Tabitha", "Tamara",
  "Tammy", "Tanya", "Tara", "Tate", "Taylor", "Ted", "Teddy", "Terence", "Teresa", "Terry",
  "Tess", "Tessa", "Thea", "Thelma", "Theo", "Theodore", "Theresa", "Thomas", "Tia", "Tiffany",
  "Tim", "Timothy", "Tina", "Tobias", "Toby", "Todd", "Tom", "Tommy", "Toni", "Tony",
  "Tracy", "Travis", "Trent", "Trevor", "Tricia", "Trinity", "Trisha", "Tristan", "Troy", "Trudy",
  "Tucker", "Tyler", "Tyra", "Ulrich", "Ulysses", "Una", "Ursula", "Val", "Valentin", "Valerie",
  "Vanessa", "Vaughn", "Velma", "Vera", "Vernon", "Veronica", "Vicky", "Victor", "Victoria", "Vince",
  "Vincent", "Viola", "Violet", "Virgil", "Virginia", "Vivian", "Vivienne", "Wade", "Walter", "Wanda",
  "Ward", "Warren", "Wayne", "Wendell", "Wendy", "Wesley", "Whitney", "Wilbur", "Wilfred", "Will",
  "Willa", "William", "Willie", "Willow", "Wilma", "Wilson", "Winifred", "Winston", "Woody", "Wyatt",
  "Xander", "Xavier", "Xena", "Yasmin", "Yolanda", "York", "Yves", "Yvette", "Yvonne", "Zach",
  "Zachary", "Zane", "Zara", "Zeke", "Zelda", "Zena", "Zoe", "Zola", "Zora", "Zack",
] as const;

function isUsable(name: string): boolean {
  return /^[A-Za-z]{2,9}$/.test(name);
}

/** Deduplicated, validated, alphabetically stable name pool. */
export const NAME_POOL: readonly string[] = Array.from(new Set(RAW_NAMES))
  .filter(isUsable)
  .sort((a, b) => a.localeCompare(b, "en"));
